##设置端口号
server:
  port: 8003

spring:
  profiles:
    active: dev
  session:
    store-type: redis
  redis:
    #host: 192.168.11.13
    host: 127.0.0.1

management:
  security:
    enabled: false



